include $(srctree)/drivers/misc/mediatek/Makefile.custom

#obj-$(CONFIG_MTK_LDVT_PMIC_WRAP) +=  tc_pwrap_ldvt.o
#obj-$(CONFIG_MTK_LDVT_PMIC_WRAP) +=  pmic_dvfs_wrapper_test.o
#obj-y +=  tc_pwrap_ldvt.o

obj-$(CONFIG_MTK_LDVT_PMIC_WRAP)  +=  pwrap_dvt.o 
