
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y	+= kd_flashlightlist.o
obj-y	+= strobe_part_id.o
obj-y	+= sub_strobe.o
obj-y	+= strobe_main_sid1_part2.o
obj-y	+= strobe_main_sid2_part1.o
obj-y	+= strobe_main_sid2_part2.o
obj-y	+= strobe_sub_sid1_part2.o
obj-y	+= strobe_sub_sid2_part1.o
obj-y	+= strobe_sub_sid2_part2.o
