# Makefile for the LDVT drivers
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MTK_LDVT_SAMPLE)   += sample/
#obj-$(CONFIG_MTK_LDVT_SPI)   += spi/
#obj-$(CONFIG_MTK_LDVT_VDEC)   += vdec/
#obj-$(CONFIG_MTK_LDVT_UDVT)   += UDVT/
#obj-$(CONFIG_MTK_LDVT_PMIC_WRAP)  += pmic_wrap/
#obj-$(CONFIG_MTK_LDVT_PMIC)   += pmic/
