/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6595. Copyright MediaTek Inc. (C) 2013.
 * Fri Feb 21 15:48:45 2014
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_TEMPERATURE_CHANNEL     0


#endif				/* _CUST_AUXADC_TOOL_H */
