/*
 * Generated by MTK SP DrvGen Version 03.13.6  for MT6595. Copyright MediaTek Inc. (C) 2013.
 * Fri Feb 21 15:48:45 2014
 * Do Not Modify the File.
 */

#define GPIO_DVDD_BPI     GPIO_VIO18
#define GPIO_DVDD_EXMD     GPIO_VIO18
