#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/include/linux/camera
obj-y				+= dummyds.o kd_camera_hw.o
