# Makefile for the linux kernel.
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y := vdec.o
obj-y   += hal/
obj-y   += verify/
#obj-$(CONFIG_MTK_LDVT_VDEC)   += hal/
#obj-$(CONFIG_MTK_LDVT_VDEC)   += verify/
