include $(srctree)/drivers/misc/mediatek/Makefile.custom

# MTK Platform Support
obj-y += mt6391.o
obj-y += mt_afe_reg.o mt_afe_clk.o mt_afe_control.o mt_afe_connection.o mt_afe_debug.o
obj-y += mt_afe_pcm_dl1.o mt_afe_pcm_capture.o mt_afe_pcm_capture2.o
obj-y += mt_afe_pcm_dl1_awb.o mt_afe_pcm_i2s0_awb.o
obj-y += mt_afe_pcm_btsco.o mt_afe_pcm_mrgrx.o mt_afe_pcm_mrgrx_awb.o
obj-y += mt_afe_pcm_hdmi.o mt_afe_pcm_hdmi_raw.o mt_afe_pcm_spdif.o
obj-y += mt_afe_pcm_routing.o mt_afe_dai_stub.o
obj-$(CONFIG_SND_SOC_MT8173_GENERIC) += mt8173_evb.o
obj-$(CONFIG_SND_SOC_MT8173_BLOFELD) += blofeld.o
obj-$(CONFIG_SND_SOC_MT8173_SLOANE) += sloane.o
