include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/misc/mediatek/smi/$(CONFIG_MTK_PLATFORM)
# ccflags-y += -Werror
obj-y += camera_isp.o
obj-y += camera_sysram.o
obj-y += camera_fdvt.o