/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT8173. Copyright MediaTek Inc. (C) 2013.
 * Fri Jan  9 17:58:18 2015
 * Do Not Modify the File.
 */

#ifndef __CUST_CLK_BUF_H__
#define __CUST_CLK_BUF_H__
typedef enum{
	CLOCK_BUFFER_DISABLE,
	CLOCK_BUFFER_SW_CONTROL,
	CLOCK_BUFFER_HW_CONTROL
}MTK_CLK_BUF_STATUS;




#endif