/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT8173. Copyright MediaTek Inc. (C) 2013.
 * Fri Jan  9 17:58:18 2015
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


